let nome = "João da Silva";
let nota1 = 7;
let nota2 = 8.5;
let peso1 = nota1 * 0.6;
let peso2 = nota2 * 0.4;
let media = peso1 + peso2;
alert(`Nome: ${nome} \nNota 1: ${nota1} \nNota 2: ${nota2}`);
alert(`Nota total: ${media}`);
let nome_1 = "William Romualdo";
let n1 = 5;
let n2 = 9.2;
let p1 = n1 * 0.6;
let p2 = n2 * 0.4;
let media_1 = p1 + p2;
alert(`Nome: ${nome_1} \nNota 1: ${n1} \nNota 2: ${n2}`);
alert(`Nota total: ${media_1}`);
let nome_2 = "Neymar Junior";
let no1 = 10;
let no2 = 8.9;
let pe1 = no1 * 0.6;
let pe2 = no2 * 0.4;
let media_2 = pe1 + pe2;
alert(`Nome: ${nome_2} \nNota 1: ${no1} \nNota 2: ${no2}`);
alert(`Nota total: ${media_2}`);